name: Build and push multi-arch Docker image

on:
  push:
    branches: [ master ] # 改为 master 分支（符合您的项目）
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 4 1 * *'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU static for multi-arch support
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Convert repository name to lowercase
      id: repo
      run: echo "repo=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

    - name: Build and push multi-arch Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./
        push: true
        tags: |
          ghcr.io/${{ steps.repo.outputs.repo }}:latest
          ghcr.io/${{ steps.repo.outputs.repo }}:${{ github.sha }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max
